In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("training_academy.db")
conn.execute("PRAGMA foreign_keys = ON;")

In [ ]:
def execute_query(conn, query, params=None):
    if params is None:
        params = []
    cursor = conn.execute(query, params)
    conn.commit()
    return cursor

def read_query(conn, query, params=None):
    if params is None:
        params = []
    return pd.read_sql_query(query, conn, params=params)

In [ ]:
execute_query(conn, """
CREATE TABLE IF NOT EXISTS departments(
    department_id INTEGER PRIMARY KEY,
    department_name TEXT NOT NULL UNIQUE
);
""")

In [ ]:
execute_query(conn, """
CREATE TABLE IF NOT EXISTS students(
    student_id INTEGER PRIMARY KEY,
    student_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    city TEXT,
    registration_date DATE NOT NULL
);
""")

In [ ]:
execute_query(conn, """
CREATE TABLE IF NOT EXISTS instructors(
    instructor_id INTEGER PRIMARY KEY,
    instructor_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    department_id INTEGER,
    FOREIGN KEY(department_id) REFERENCES departments(department_id)
);
""")

In [ ]:
execute_query(conn, """
CREATE TABLE IF NOT EXISTS courses(
    course_id INTEGER PRIMARY KEY,
    course_name TEXT NOT NULL,
    department_id INTEGER,
    instructor_id INTEGER,
    fee REAL NOT NULL CHECK(fee>=0),
    level TEXT CHECK(level IN ('Beginner','Intermediate','Advanced')),
    FOREIGN KEY(department_id) REFERENCES departments(department_id),
    FOREIGN KEY(instructor_id) REFERENCES instructors(instructor_id)
);
""")

In [ ]:
execute_query(conn, """
CREATE TABLE IF NOT EXISTS enrollments(
    enrollment_id INTEGER PRIMARY KEY,
    student_id INTEGER,
    course_id INTEGER,
    enrollment_date DATE NOT NULL,
    status TEXT DEFAULT 'Active' CHECK(status IN ('Active','Completed','Cancelled')),
    UNIQUE(student_id,course_id),
    FOREIGN KEY(student_id) REFERENCES students(student_id),
    FOREIGN KEY(course_id) REFERENCES courses(course_id)
);
""")

In [ ]:
execute_query(conn, """
CREATE TABLE IF NOT EXISTS payments(
    payment_id INTEGER PRIMARY KEY,
    enrollment_id INTEGER UNIQUE,
    amount REAL NOT NULL CHECK(amount>=0),
    payment_date DATE NOT NULL,
    payment_status TEXT CHECK(payment_status IN ('Paid','Pending','Refunded')),
    FOREIGN KEY(enrollment_id) REFERENCES enrollments(enrollment_id)
);
""")

In [ ]:
read_query(conn, """
SELECT name
FROM sqlite_master
WHERE type='table';
""")

          name
0  departments
1     students
2  instructors
3      courses
4  enrollments
5     payments

In [ ]:
execute_query(conn, """
INSERT INTO departments VALUES
(1,'Data Science'),
(2,'Software Engineering'),
(3,'Business Analytics');
""")

In [ ]:
execute_query(conn, """
INSERT INTO students VALUES
(1,'Rahul Kumar','rahul.kumar@example.com','Patna','2026-01-05'),
(2,'Priya Singh','priya.singh@example.com','Kolkata','2026-01-06'),
(3,'Amit Raj','amit.raj@example.com','Delhi','2026-01-07'),
(4,'Sneha Verma','sneha.verma@example.com','Patna','2026-01-10'),
(5,'Aditya Sharma','aditya.sharma@example.com','Mumbai','2026-01-12');
""")

In [ ]:
execute_query(conn, """
INSERT INTO instructors VALUES
(1,'Dr. Meera Iyer','meera.iyer@example.com',1),
(2,'Arjun Sen','arjun.sen@example.com',2),
(3,'Kavita Rao','kavita.rao@example.com',3);
""")

In [ ]:
execute_query(conn, """
INSERT INTO courses VALUES
(101,'Python for Beginners',2,2,4999,'Beginner'),
(102,'SQL and RDBMS Masterclass',1,1,6999,'Beginner'),
(103,'Machine Learning Basics',1,1,11999,'Intermediate'),
(104,'Business Dashboarding',3,3,8999,'Intermediate'),
(105,'Advanced Data Engineering',1,1,15999,'Advanced');
""")

In [ ]:
execute_query(conn, """
INSERT INTO enrollments VALUES
(1001,1,101,'2026-02-01','Active'),
(1002,1,102,'2026-02-03','Completed'),
(1003,2,102,'2026-02-04','Active'),
(1004,3,103,'2026-02-05','Active'),
(1005,4,104,'2026-02-07','Cancelled');
""")

In [ ]:
execute_query(conn, """
INSERT INTO payments VALUES
(501,1001,4999,'2026-02-01','Paid'),
(502,1002,6999,'2026-02-03','Paid'),
(503,1003,6999,'2026-02-04','Pending'),
(504,1004,11999,'2026-02-05','Paid'),
(505,1005,0,'2026-02-07','Refunded');
""")

In [ ]:
read_query(conn,"SELECT * FROM departments")

   department_id       department_name
0              1          Data Science
1              2  Software Engineering
2              3    Business Analytics

In [ ]:
read_query(conn,"SELECT * FROM students")

,student_id,student_name,email,city,registration_date
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-06
2,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-07
3,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-10
4,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-12

In [ ]:
read_query(conn,"SELECT * FROM instructors")

   instructor_id instructor_name                   email  department_id
0              1  Dr. Meera Iyer  meera.iyer@example.com              1
1              2       Arjun Sen   arjun.sen@example.com              2
2              3      Kavita Rao  kavita.rao@example.com              3

In [ ]:
read_query(conn,"SELECT * FROM courses")

,course_id,course_name,department_id,instructor_id,fee,level
0,101,Python for Beginners,2,2,4999.0,Beginner
1,102,SQL and RDBMS Masterclass,1,1,6999.0,Beginner
2,103,Machine Learning Basics,1,1,11999.0,Intermediate
3,104,Business Dashboarding,3,3,8999.0,Intermediate
4,105,Advanced Data Engineering,1,1,15999.0,Advanced

In [ ]:
read_query(conn,"SELECT * FROM enrollments")

   enrollment_id  student_id  course_id enrollment_date     status
0           1001           1        101      2026-02-01     Active
1           1002           1        102      2026-02-03  Completed
2           1003           2        102      2026-02-04     Active
3           1004           3        103      2026-02-05     Active
4           1005           4        104      2026-02-07  Cancelled

In [ ]:
read_query(conn,"SELECT * FROM payments")

   payment_id  enrollment_id   amount payment_date payment_status
0         501           1001   4999.0   2026-02-01           Paid
1         502           1002   6999.0   2026-02-03           Paid
2         503           1003   6999.0   2026-02-04        Pending
3         504           1004  11999.0   2026-02-05           Paid
4         505           1005      0.0   2026-02-07       Refunded

In [ ]:
read_query(conn, "SELECT * FROM students")

,student_id,student_name,email,city,registration_date
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-06
2,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-07
3,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-10
4,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-12

In [ ]:
read_query(conn, "SELECT student_name, email, city FROM students")

    student_name                      email     city
0    Rahul Kumar    rahul.kumar@example.com    Patna
1    Priya Singh    priya.singh@example.com  Kolkata
2       Amit Raj       amit.raj@example.com    Delhi
3    Sneha Verma    sneha.verma@example.com    Patna
4  Aditya Sharma  aditya.sharma@example.com   Mumbai

In [ ]:
read_query(conn, "SELECT * FROM students WHERE city='Patna'")

   student_id student_name                    email   city registration_date
0           1  Rahul Kumar  rahul.kumar@example.com  Patna        2026-01-05
1           4  Sneha Verma  sneha.verma@example.com  Patna        2026-01-10

In [ ]:
read_query(conn, "SELECT * FROM courses WHERE fee > 7000")

,course_id,course_name,department_id,instructor_id,fee,level
0,103,Machine Learning Basics,1,1,11999.0,Intermediate
1,104,Business Dashboarding,3,3,8999.0,Intermediate
2,105,Advanced Data Engineering,1,1,15999.0,Advanced

In [ ]:
read_query(conn, "SELECT * FROM courses WHERE level='Beginner'")

,course_id,course_name,department_id,instructor_id,fee,level
0,101,Python for Beginners,2,2,4999.0,Beginner
1,102,SQL and RDBMS Masterclass,1,1,6999.0,Beginner

In [ ]:
read_query(conn, "SELECT * FROM students ORDER BY student_name ASC")

,student_id,student_name,email,city,registration_date
0,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-12
1,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-07
2,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-06
3,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05
4,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-10

In [ ]:
read_query(conn, "SELECT course_name, fee FROM courses ORDER BY fee DESC LIMIT 3")

                 course_name      fee
0  Advanced Data Engineering  15999.0
1    Machine Learning Basics  11999.0
2      Business Dashboarding   8999.0

In [ ]:
read_query(conn, "SELECT DISTINCT city FROM students")

      city
0    Patna
1  Kolkata
2    Delhi
3   Mumbai

In [ ]:
read_query(conn, "SELECT * FROM payments WHERE payment_status='Pending'")

   payment_id  enrollment_id  amount payment_date payment_status
0         503           1003  6999.0   2026-02-04        Pending

In [ ]:
read_query(conn, "SELECT * FROM enrollments WHERE status='Active'")

   enrollment_id  student_id  course_id enrollment_date  status
0           1001           1        101      2026-02-01  Active
1           1003           2        102      2026-02-04  Active
2           1004           3        103      2026-02-05  Active

In [ ]:
execute_query(
    conn,
    """
    INSERT INTO students(student_id, student_name, email, city, registration_date)
    VALUES (?, ?, ?, ?, ?)
    """,
    (6, "Rohan Das", "rohan.das@example.com", "Pune", "2026-02-15")
)

In [ ]:
read_query(conn, "SELECT * FROM students WHERE student_name='Rohan Das'")

   student_id student_name                  email  city registration_date
0           6    Rohan Das  rohan.das@example.com  Pune        2026-02-15

In [ ]:
execute_query(
    conn,
    """
    UPDATE students
    SET city=?
    WHERE student_name=?
    """,
    ("Bengaluru", "Rohan Das")
)

In [ ]:
read_query(conn, "SELECT * FROM students WHERE student_name='Rohan Das'")

   student_id student_name                  email       city registration_date
0           6    Rohan Das  rohan.das@example.com  Bengaluru        2026-02-15

In [ ]:
execute_query(
    conn,
    """
    DELETE FROM students
    WHERE student_name=?
    """,
    ("Rohan Das",)
)

In [ ]:
read_query(conn, "SELECT * FROM students")

,student_id,student_name,email,city,registration_date
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-06
2,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-07
3,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-10
4,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-12

In [ ]:
try:
    execute_query(
        conn,
        """
        INSERT INTO students(student_id, student_name, email, city, registration_date)
        VALUES (?, ?, ?, ?, ?)
        """,
        (7, "Test User", "rahul.kumar@example.com", "Chennai", "2026-03-01")
    )
except Exception as e:
    print(e)

UNIQUE constraint failed: students.email

In [ ]:
try:
    execute_query(
        conn,
        """
        INSERT INTO enrollments(enrollment_id, student_id, course_id, enrollment_date, status)
        VALUES (?, ?, ?, ?, ?)
        """,
        (1006, 99, 101, "2026-03-01", "Active")
    )
except Exception as e:
    print(e)

FOREIGN KEY constraint failed

In [ ]:
try:
    execute_query(
        conn,
        """
        INSERT INTO courses(course_id, course_name, department_id, instructor_id, fee, level)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (106, "Negative Fee Course", 1, 1, -1000, "Beginner")
    )
except Exception as e:
    print(e)

CHECK constraint failed: fee>=0

In [ ]:
try:
    execute_query(
        conn,
        """
        INSERT INTO enrollments(enrollment_id, student_id, course_id, enrollment_date, status)
        VALUES (?, ?, ?, ?, ?)
        """,
        (1007, 2, 103, "2026-03-02", "Started")
    )
except Exception as e:
    print(e)

CHECK constraint failed: status IN ('Active','Completed','Cancelled')

In [ ]:
read_query(conn, "PRAGMA table_info(students)")

   cid               name     type  notnull dflt_value  pk
0    0         student_id  INTEGER        0       None   1
1    1       student_name     TEXT        1       None   0
2    2              email     TEXT        1       None   0
3    3               city     TEXT        0       None   0
4    4  registration_date     DATE        1       None   0

In [ ]:
read_query(conn, "PRAGMA table_info(courses)")

   cid           name     type  notnull dflt_value  pk
0    0      course_id  INTEGER        0       None   1
1    1    course_name     TEXT        1       None   0
2    2  department_id  INTEGER        0       None   0
3    3  instructor_id  INTEGER        0       None   0
4    4            fee     REAL        1       None   0
5    5          level     TEXT        0       None   0

In [ ]:
read_query(conn, "PRAGMA table_info(enrollments)")

   cid             name     type  notnull dflt_value  pk
0    0    enrollment_id  INTEGER        0       None   1
1    1       student_id  INTEGER        0       None   0
2    2        course_id  INTEGER        0       None   0
3    3  enrollment_date     DATE        1       None   0
4    4           status     TEXT        0   'Active'   0

In [ ]:
read_query(conn, "PRAGMA table_info(payments)")

   cid            name     type  notnull dflt_value  pk
0    0      payment_id  INTEGER        0       None   1
1    1   enrollment_id  INTEGER        0       None   0
2    2          amount     REAL        1       None   0
3    3    payment_date     DATE        1       None   0
4    4  payment_status     TEXT        0       None   0

In [ ]:
read_query(conn, "PRAGMA foreign_key_list(instructors)")

,id,seq,table,from,to,on_update,on_delete,match
0,0,0,departments,department_id,department_id,NO ACTION,NO ACTION,NONE

In [ ]:
read_query(conn, "PRAGMA foreign_key_list(courses)")

,id,seq,table,from,to,on_update,on_delete,match
0,0,0,instructors,instructor_id,instructor_id,NO ACTION,NO ACTION,NONE
1,1,0,departments,department_id,department_id,NO ACTION,NO ACTION,NONE

In [ ]:
read_query(conn, "PRAGMA foreign_key_list(enrollments)")

   id  seq     table        from          to  on_update  on_delete match
0   0    0   courses   course_id   course_id  NO ACTION  NO ACTION  NONE
1   1    0  students  student_id  student_id  NO ACTION  NO ACTION  NONE

In [ ]:
read_query(conn, "PRAGMA foreign_key_list(payments)")

,id,seq,table,from,to,on_update,on_delete,match
0,0,0,enrollments,enrollment_id,enrollment_id,NO ACTION,NO ACTION,NONE

In [ ]:
execute_query(conn, """
CREATE TABLE IF NOT EXISTS course_feedback(
    feedback_id INTEGER PRIMARY KEY,
    enrollment_id INTEGER,
    rating INTEGER CHECK(rating BETWEEN 1 AND 5),
    comments TEXT,
    feedback_date DATE NOT NULL,
    FOREIGN KEY(enrollment_id) REFERENCES enrollments(enrollment_id)
);
""")

In [ ]:
execute_query(conn, """
INSERT INTO course_feedback VALUES
(1,1001,5,'Excellent course','2026-02-10'),
(2,1003,4,'Very informative','2026-02-12'),
(3,1004,3,'Good but needs more examples','2026-02-15');
""")

In [ ]:
read_query(conn,"SELECT * FROM course_feedback")

,feedback_id,enrollment_id,rating,comments,feedback_date
0,1,1001,5,Excellent course,2026-02-10
1,2,1003,4,Very informative,2026-02-12
2,3,1004,3,Good but needs more examples,2026-02-15

In [ ]:
read_query(conn,"SELECT * FROM course_feedback WHERE rating>=4")

   feedback_id  enrollment_id  rating          comments feedback_date
0            1           1001       5  Excellent course    2026-02-10
1            2           1003       4  Very informative    2026-02-12

In [ ]:
try:
    execute_query(conn, """
    INSERT INTO course_feedback
    VALUES
    (4,1002,6,'Invalid Rating','2026-02-18');
    """)
except Exception as e:
    print(e)

CHECK constraint failed: rating BETWEEN 1 AND 5

In [ ]:
read_query(conn,"PRAGMA table_info(course_feedback)")

   cid           name     type  notnull dflt_value  pk
0    0    feedback_id  INTEGER        0       None   1
1    1  enrollment_id  INTEGER        0       None   0
2    2         rating  INTEGER        0       None   0
3    3       comments     TEXT        0       None   0
4    4  feedback_date     DATE        1       None   0

In [ ]:
read_query(conn,"PRAGMA foreign_key_list(course_feedback)")

,id,seq,table,from,to,on_update,on_delete,match
0,0,0,enrollments,enrollment_id,enrollment_id,NO ACTION,NO ACTION,NONE

In [ ]:
tables = [
    "departments",
    "students",
    "instructors",
    "courses",
    "enrollments",
    "payments",
    "course_feedback"
]

for table in tables:
    print(f"\n----- {table.title()} -----")
    display(read_query(conn, f"SELECT * FROM {table}"))

----- Departments -----

   department_id       department_name
0              1          Data Science
1              2  Software Engineering
2              3    Business Analytics

----- Students -----

,student_id,student_name,email,city,registration_date
0,1,Rahul Kumar,rahul.kumar@example.com,Patna,2026-01-05
1,2,Priya Singh,priya.singh@example.com,Kolkata,2026-01-06
2,3,Amit Raj,amit.raj@example.com,Delhi,2026-01-07
3,4,Sneha Verma,sneha.verma@example.com,Patna,2026-01-10
4,5,Aditya Sharma,aditya.sharma@example.com,Mumbai,2026-01-12

----- Instructors -----

   instructor_id instructor_name                   email  department_id
0              1  Dr. Meera Iyer  meera.iyer@example.com              1
1              2       Arjun Sen   arjun.sen@example.com              2
2              3      Kavita Rao  kavita.rao@example.com              3

----- Courses -----

,course_id,course_name,department_id,instructor_id,fee,level
0,101,Python for Beginners,2,2,4999.0,Beginner
1,102,SQL and RDBMS Masterclass,1,1,6999.0,Beginner
2,103,Machine Learning Basics,1,1,11999.0,Intermediate
3,104,Business Dashboarding,3,3,8999.0,Intermediate
4,105,Advanced Data Engineering,1,1,15999.0,Advanced

----- Enrollments -----

   enrollment_id  student_id  course_id enrollment_date     status
0           1001           1        101      2026-02-01     Active
1           1002           1        102      2026-02-03  Completed
2           1003           2        102      2026-02-04     Active
3           1004           3        103      2026-02-05     Active
4           1005           4        104      2026-02-07  Cancelled

----- Payments -----

   payment_id  enrollment_id   amount payment_date payment_status
0         501           1001   4999.0   2026-02-01           Paid
1         502           1002   6999.0   2026-02-03           Paid
2         503           1003   6999.0   2026-02-04        Pending
3         504           1004  11999.0   2026-02-05           Paid
4         505           1005      0.0   2026-02-07       Refunded

----- Course_Feedback -----

,feedback_id,enrollment_id,rating,comments,feedback_date
0,1,1001,5,Excellent course,2026-02-10
1,2,1003,4,Very informative,2026-02-12
2,3,1004,3,Good but needs more examples,2026-02-15